version: '3.8'

services:

  web:
    build: .
    ports:
      - 443:443
    command: uvicorn app.main:app --host 0.0.0.0 --port 443 --ssl-keyfile /usr/src/ssl/key.pem --ssl-certfile /usr/src/ssl/cert.pem  --reload
    volumes:
      - ./app:/usr/src/app
      - ./ssl:/usr/src/ssl
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    env_file:
      - .env
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A app.worker.celery worker --loglevel=info
    volumes:
      - .:/usr/src
    user: "celery" 
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
  redis:
    image: redis:7
