api:
  port: 8000
  environment: prod

im:
  endpoint: https://im.egi.eu/im
  cloud_provider:
    type: OpenStack
    host: "https://identity.brno.openstack.cloud.e-infra.cz"
    username: "demo.egi.eu"
    auth_version: "3.x_oidc_access_token"
    tenant: "openid"
    domain: "vo.eosc-data-commons.eu"
  wait:
    max_time: 36000 # 10h
    sleep: 30
    max_retries: 3


