dispatcher:
  repo: https://github.com/EOSC-Data-Commons/Dispatcher.git
  branch: master
  dir: /opt/edc/dispatcher

git:
  # macos
  # backend: /Library/Developer/CommandLineTools/usr/libexec/git-core/git-http-backend
  # linux 
  backend: /usr/libexec/git-core/git-http-backend
  repos: /tmp/git/repos

nginx:
  prefix: nginx
  etc: /etc 
  logs: /var/log
  pid: /tmp/nginx.pid
  fcgi: /tmp/fcgiwrap.socket
  cert: /etc/letsencrypt 


api:
  port: 8000
  environment: dev

im:
  endpoint: https://appsgrycap.i3m.upv.es/im-dev/
  # We can set in in secret vars to avoid exposing credentials
  cloud_provider:
    host: "https://keystone:5000/"
    username: "your_app_credential_id"
    auth_version: 3.x_appcred
    tenant: "project_name"
    password: "your_app_credential_secret"
    domain: default
    # Optional
    # region: RegionOne