---
- hosts: dispatchers
  become: true
  become_user: root
  tasks:
    - name: Copy local version of repo
      synchronize:
        src: ../../
        dest: "{{ dispatcher.dir }}"

    - name: Install docker-compose-init.yml
      ansible.builtin.template:
        src: docker-compose-init.yml.j2
        dest: "{{ dispatcher.dir }}/docker-compose-init.yml"


    - name: Install docker-compose.yml
      ansible.builtin.template:
        src: docker-compose.yml.j2
        dest: "{{ dispatcher.dir }}/docker-compose.yml"

    - name: Install ocm.json
      ansible.builtin.template:
        src: ocm.json.j2
        dest: "{{ dispatcher.dir }}/nginx/ocm.json"

    - name: Install nginx.conf
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: "{{ dispatcher.dir }}/nginx/nginx.conf"

    - name: Install api-config file
      ansible.builtin.template:
        src: config.py.j2
        dest: "{{ dispatcher.dir }}/app/config.py"

    - name: Start nginx_helper for certbot
      community.docker.docker_compose_v2:
        project_src: "{{ dispatcher.dir }}"
        state: present
        files: ["docker-compose-init.yml"]
        services: ["nginx_helper"]
        remove_orphans: true

    - name: Run certbot
      community.docker.docker_compose_v2_run:
        project_src: "{{ dispatcher.dir }}"
        files: ["docker-compose-init.yml"]
        service: "certbot"

    - name: Run modify_cert
      community.docker.docker_compose_v2_run:
        project_src: "{{ dispatcher.dir }}"
        files: ["docker-compose-init.yml"]
        service: "modify_cert"

    - name: Ensure docker-compose app is running
      community.docker.docker_compose_v2:
        project_src: "{{ dispatcher.dir }}"
        state: present 
        build: "always"
    
    - name: Stop docker init
      community.docker.docker_compose_v2:
        project_src: "{{ dispatcher.dir }}"
        state: absent 
        files: ["docker-compose-init.yml"]

    - name: Clean dangling images
      community.docker.docker_prune:
        images: true
        images_filters:
          dangling: true
