dispatchers:
  hosts:
    player.eosc-data-commons.eu:
      ansible_user: ubuntu
    dev1.player.eosc-data-commons.eu:
      ansible_user: ubuntu
    dev2.player.eosc-data-commons.eu:
      ansible_user: ubuntu
    dev3.player.eosc-data-commons.eu:
      ansible_user: ubuntu
    dev4.player.eosc-data-commons.eu:
      ansible_user: ubuntu
    dev.matchmaker.eosc-data-commons.eu:
      ansible_user: ubuntu
